language: php

notifications:
    email:
        recipients:
            - dev@dmk-ebusiness.de
        on_success: change
        on_failure: always

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

env:
    - TYPO3_VERSION="^8.7.0"
    - TYPO3_VERSION="^9.5.0"

matrix:
    exclude:
        - php: 7.0
          env: TYPO3_VERSION="^9.5.0"
        - php: 7.1
          env: TYPO3_VERSION="^9.5.0"

sudo: false

addons:
    apt:
        packages:
            - parallel

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update --1
    - composer --version

before_script:
    - composer require typo3/minimal="$TYPO3_VERSION"
    # Restore composer.json
    - git checkout composer.json
    - export TYPO3_PATH_WEB=$PWD/.Build/Web
    - cp $PWD/tests/fixtures/LocalConfiguration.php $PWD/.Build/Web/typo3conf/LocalConfiguration.php

script:
    - >
        echo;
        echo "Running unit tests";
        .Build/bin/phpunit -c phpunit.xml.dist --coverage-text --coverage-clover=.Build/coverage.clover
    - >
        echo;
        echo "Running php lint";
        find . -name \*.php ! -path "./.Build/*" -and ! -path "./Resources/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
